version: '3.8'
services:
  movies:
    image: anandock/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: anandock/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: anandock/paytmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: anandock/paytmrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
